name: ticketpond-prod
services:
  database:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ticketpond
    volumes:
      - db:/var/lib/postgresql/data
  backend:
    build: .
    ports:
      - '3001:3001'
    env_file:
      - ./.env
    depends_on:
      - database
volumes:
  db:
